name: CD to Docker Hub

on:
  create:
    tags:
      - "v*.*.*"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ DOCKER_HUB_USERNAME }}
          password: ${{ DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with: 
          version: v0.7.0
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
        
          context: ./Software Implementations/Flask-API/
          file: ./Software Implementations/Flask-API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/group-one-ner:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
